openapi: 3.0.0


info:
  title: Datasourcers API

  description: |
    # Ferrea Datasource
    This microservice expose an API that allows external datasources to be integrated with Ferrea.
    Given an ISBN, it gather information from multiple source, in order to import them in the application.

  version: 1.0.0

  contact:
    "name": "Eugenio Grimoldi"
    "url": "https://github.com/Grimoldi/ferrea-datasources"

  license:
    name: MIT licence
    url: https://mit-license.org/


servers:
  - url: https://ferrea.local
    description: Development local server


paths:
  api/v1/books/{isbn}:
    $ref: "paths/datasource.yaml#/GetBook"

  _/health:
    $ref: "paths/probes.yaml#/Liveness"

  _/ready:
    $ref: "paths/probes.yaml#/Readiness"


components:
  schemas:
    BookDatasource:
      $ref: "schemas/datasource.yaml#/BookDatasource"

    ValidationError:
      $ref: "schemas/validation_error.yaml#/ValidationError"

    Probe:
      $ref: "schemas/probe.yaml#/Probe"


tags: 
  - name: books
    description: Book related operations.

  - name: probes
    description: internal probes.
