FerreaError:
  type: object
  properties:
    detail:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
  required:
    - detail
  additionalProperties: false
