Error:
  type: object
  properties:
    detail:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
  required:
    - detail
  additionalProperties: false

BookDatasource:
  type: object
  required:
    - title
    - author
  properties:
    title:
      type: string
    author:
      type: array
      items:
        type: string
    publishing:
      type: string
    published_on:
      type: integer
      minimum: 1
    cover:
      type: string
    plot:
      type: string
    language:
      type: array
      items:
        type: string
    book_format:
      type: string
    author_portrait:
      type: string
