name: Build and Push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

env:
  DOCKER_REPO: grimoldi
  FERREA_MICROSERVICE: datasources

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # preliminary steps
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/ferrea-${{ env.FERREA_MICROSERVICE }}
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Install python, poetry and export requirements
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      # load cached venv if cache exists
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install export plugin
        run: poetry self add poetry-plugin-export

      # Install dependencies if cache does not exist
      - name: Export requirements.txt
        run: poetry export -o ./requirements.txt --without-hashes --quiet --no-interaction

      - name: List files in the repository
        run: |
          ls      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
          # add otherwise the requirements.txt file would not be found
          # https://github.com/docker/build-push-action?tab=readme-ov-file#git-context
          context: .