name: Interrogate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-docstrings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Interrogate check
        uses: JackMcKew/python-interrogate-check@main
        with:
            path: 'src'